### ISSUE TITLE
where is the most recent authoritative list of Citywide Perf Indicators?

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-plans#12]
need to ask the budget office

**Comment by Jesse-Rodriguez** [comment]
Are we looking for the Dashboard Measures?  Those would be here: http://www.ci.austin.tx.us/budget/eperf/index.cfm?fuseaction=home.dashboardmeasures

**Comment by haileypate** [comment]
awesome, thanks Jesse! I will cross-reference these from the ones that I found on the open data portal to make sure they're included.

**Comment by Jesse-Rodriguez** [comment]
The Dashboard Measures are included in the overall KPI list!
