### ISSUE TITLE
Other Teams Not On GitHub

### ISSUE THREAD

**Issue by wrays** [cityofaustin/open-data-plans#17]
@haileypate So the Training and Resources Team has a GitHub page, but they are working in Trello. So that means unless you're in that group, you can't see what they're doing.

So all the team leaders aren't on the same page with using GitHub not only for the actually documentation, but for the preparation and discussion.

We should be, I think.

**Comment by wrays** [comment]
Says he who is working in SharePoint for HHSD :-)

**Comment by haileypate** [comment]
@wrays, I hear you. Open is better and transitioning all open data projects to GitHub is definitely a goal of ours. 

There is often a learning curve when it comes to new collaboration tools, so we don't expect all teams to become fully active on GitHub right away. For some teams who aren't completely comfortable today, we've encouraged them to continue using the collaboration tools with which they are most comfortable. Sort of like you and your Sharepoint, my friend ;) 

**If you aren't in the training group, here's how you can see what they're doing:**
- The training team does have a public github repo where they are developing a training website. You can find the repo [here](https://github.com/cityofaustin/open-data-training) and submit feedback/questions/issues to them [here](https://github.com/cityofaustin/open-data-training/issues). 
- The training team is documenting their project contacts, scope and charter, and progress reports publicly in github. You may access that content [here](http://open-data-sprints.readthedocs.io/en/latest/project-training.html) and suggest edits [here](https://github.com/cityofaustin/open-data-sprints/blob/master/docs/project-training.rst). 
- Join their Trello group. All City Staff are welcome to join and participate as long as their contributions remain in scope. Please send me an email if you are interested and I will let Happiness know that you are interested in accessing her board.

**Coming soon:**
Last week, Happiness (the training project coordinator) expressed interest in having her team's trello activity posted automatically in GitHub for public review. It's on our to-do list (I am the hold up, I have a few other things ahead of this) and we hope to deploy in the coming weeks. 

If I can provide anything further on this, please let me know.
