### ISSUE TITLE
Comment on Plan Problem Statement

### ISSUE THREAD

**Issue by wrays** [cityofaustin/open-data-plans#9]
Comment on this problem statement:

"Increased transparency and public collaboration are key goals of Austin’s Open Data Initiative. In pursuit of these goals, City Departments developed open data plans and inventories during previous sprints. Currently, the format and quality of both products vary widely across departments."

I think this problem statement also needs to emphasize the internal value of open data to each department to help it develop data-driven decision making.

**Comment by haileypate** [comment]
absolutely... this is really great feedback. @wrays, do you have any recommended language, or would you like me to draft an edit for review by the group?

**Comment by wrays** [comment]
Building on this -- efficiency and effectiveness in government
https://www.whitehouse.gov/Open

**Comment by haileypate** [comment]
i love this! Not seeing immediately the best place to work this language into the document, especially with regard to the department-level value for internal efficiency and decision making. 

if you have a specific revision you'd like make to the [Problem Statement](http://open-data-sprints.readthedocs.io/en/latest/project-open-data-plans.html#problem-statement), please let me know! I'll need the language you'd like to add/replace and the location of where to insert it.

**Comment by wrays** [comment]
@haileypate see insertion of sentence here that I think encapsulates the thought

Increased transparency, public collaboration, and data-driven decision making are key goals of Austin’s Open Data Initiative. **When fully realized this City-wide project will benefit both the community as well as City government to become more efficient and effective.**  In pursuit of these goals, City Departments developed open data plans and inventories during previous sprints. Currently, the format and quality of both products vary widely across departments.

**Comment by haileypate** [comment]
thank you! i added the text as you recommended, as part of the edit described [here](https://github.com/cityofaustin/open-data-sprints/pull/29/commits). 

If I can provide anything further on this, please let me know!
